### ISSUE TITLE
Viewing wrong answer

### ISSUE THREAD

**Issue by skarrman** [istodaymeatballsday/Web#12]
<img width="1680" alt="Screenshot 2019-11-07 at 09 07 11" src="https://user-images.githubusercontent.com/21331930/68371040-16c79480-013e-11ea-831f-52361789b794.png">
<img width="419" alt="Screenshot 2019-11-07 at 09 08 44" src="https://user-images.githubusercontent.com/21331930/68371086-3494f980-013e-11ea-997c-265093f2fd43.png">

**Comment by anthager** [comment]
Okay so the issue here is that the wonderful staff at express changed order of english and swedish today. Which makes the https://github.com/istodaymeatballsday/Web/blob/03e2cee3af9de34a607d5d1071426f33cc75341c/scripts/rebuild.py#L59 regex fail

**Comment by anthager** [comment]
You mind throw up a pr? @skarrman

**Comment by skarrman** [comment]
Yep.

**Comment by anthager** [comment]
😡

**Comment by skarrman** [comment]
I'm on it

**Comment by skarrman** [comment]
Fixed by #13
